
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  namespace: netflix
  labels:
    role: netflix
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: netflix
  template:
    metadata:
      labels:
        role: netflix
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: netflix
        image: 891377007972.dkr.ecr.ap-south-1.amazonaws.com/netflix-demo:3
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://amanpathakdevops.study/api/tasks"
        ports:
        - containerPort: 3000
